### ISSUE TITLE
LAB_02b-Manage_Governance_via_Azure_Policy.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es#12]
lab02b.png
Arrows and squares are wrongly placed, should be adapted to the text.

[LAB_02b-Manage_Governance_via_Azure_Policy.md.pdf](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es/files/7755312/LAB_02b-Manage_Governance_via_Azure_Policy.md.pdf)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The loc image Arrows and squares same with source. Rejected.
ES-ES:
![image](https://user-images.githubusercontent.com/49666210/184785758-95b79136-1665-4bf1-a30b-bc06e3017d68.png)

Source:
![image](https://user-images.githubusercontent.com/49666210/184785807-103e3d47-dfd4-4fec-9f2c-182682e07b69.png)
