### ISSUE TITLE
LAB_09a-Implement_Web_Apps.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es#15]
lab09a.png
Text overextends the background square, should be adapted, maybe split into 2 lines.

[LAB_09a-Implement_Web_Apps.md.pdf](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es/files/7755317/LAB_09a-Implement_Web_Apps.md.pdf)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691937

**Comment by stonezy123** [comment]
The image fixed. close it.
![image](https://user-images.githubusercontent.com/49666210/190939802-fd6fa217-2de9-437f-bfce-ff7dec474e6b.png)
