### ISSUE TITLE
Several missing images in /media dir

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es#16]
In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es/main/Instructions/Labs/LAB_03d-Manage_Azure_Resources_by_Using_Azure_CLI.md

We are missing file: ../media/lab03d.png

In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es/main/Instructions/Labs/LAB_10-Implement_Data_Protection.md

We are missing file: ../media/lab10.png

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The locfile shown lnLoclization status, waiting for checkIn.  [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtTcGFuaXNoPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7SXMgSW4gTGlzdDtsYWIxMC5wbmcsbGFiMDNkLnBuZzwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by chriscarty00** [comment]
[ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtTcGFuaXNoPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7SXMgSW4gTGlzdDtsYWIxMC5wbmcsbGFiMDNkLnBuZzwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) Still Inloc

**Comment by stonezy123** [comment]
The image check In.
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es/tree/OLPRODLOC/Instructions/media
